version: '2'

networks:
  hospital:

services:
  redis1:
    image: 'redis:latest'
    container_name: redis.hosp1.neuralmed.com
    command: redis-server --requirepass hosp1neuralmed
    ports:
      - "6379:6379"
    networks:
      - hospital

  redis2:
    image: 'redis:latest'
    container_name: redis.hosp2.neuralmed.com
    command: redis-server --requirepass hosp2neuralmed
    ports:
      - "6380:6379"
    networks:
      - hospital

  redis3:
    image: 'redis:latest'
    container_name: redis.hosp3.neuralmed.com
    command: redis-server --requirepass hosp3neuralmed
    ports:
      - "6381:6379"
    networks:
      - hospital